[package]
name = "book_metadata_finder"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.14", features = ["blocking", "json"] }
scraper = "0.14.0"
serde = { version = "1.0", features = ["derive"] }
